# Generated by Django 3.2.7 on 2021-10-03 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrder',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ammount', models.PositiveIntegerField()),
                ('shipPrice', models.PositiveIntegerField(default=50)),
                ('totalAmmount', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Decline', 'Decline')], max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentOrder',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ammount', models.PositiveIntegerField()),
                ('shipPrice', models.PositiveIntegerField(default=50)),
                ('totalAmmount', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('orderStatus', models.CharField(blank=True, choices=[('Dispatch', 'Dispatch'), ('Shipment', 'Shipment'), ('Arrives at', 'Arrives at'), ('Complete', 'Complete')], default='OrderConfirm', max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('orderSeller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.allorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuccessOrder',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ammount', models.PositiveIntegerField()),
                ('shipPrice', models.PositiveIntegerField(default=50)),
                ('totalAmmount', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('orderSeller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.currentorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ammount', models.PositiveIntegerField()),
                ('shipPrice', models.PositiveIntegerField(default=50)),
                ('totalAmmount', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('orderSeller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.allorder')),
                ('orderUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.currentorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
